ARG VERSION

FROM informatievlaanderen/codelijsten-generator-base:${VERSION} as BUILD

WORKDIR /app

ADD . /app

RUN npm run build
RUN npm install -g @oslo-flanders/codelist-generator

FROM node:24-alpine

WORKDIR /app
EXPOSE 3000

COPY --from=BUILD /app/.output /app
# Include the codelijst-template in the build
COPY --from=BUILD /app/codelijst-template.xlsx /app/codelijst-template.xlsx
COPY --from=BUILD /usr/local/lib/node_modules/@oslo-flanders/codelist-generator /usr/local/lib/node_modules/@oslo-flanders/codelist-generator
# Needed so that we can run the oslo-codelist-generator in a child process
RUN ln -s /usr/local/lib/node_modules/@oslo-flanders/codelist-generator/bin/runner.js /usr/local/bin/oslo-codelist-generator \
    && chmod +x /usr/local/bin/oslo-codelist-generator
CMD ["node", "./server/index.mjs"]

