ARG VERSION

FROM informatievlaanderen/codelijsten-base:${VERSION} as BUILD

WORKDIR /app

ADD . /app

RUN npm run build

FROM node:24-alpine

WORKDIR /app
EXPOSE 3000

COPY --from=BUILD /app/.output /app
CMD ["node", "./server/index.mjs"]

